terraform plan

diff --git a/.github/workflows/infra-plan-apply.yml b/.github/workflows/infra-plan-apply.yml
--- a/.github/workflows/infra-plan-apply.yml
+++ b/.github/workflows/infra-plan-apply.yml
@@ -23,8 +23,42 @@ env:
   ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
 
 jobs:
-  test_schedule:
+  terraform-plan:
+    name: Terraform Plan
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: infrastructure
+
     steps:
-      - name: Every time
-        run: echo "This step will always run"
+      - name: Checkout
+        uses: actions/checkout@v4
+      
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v4
+        with:
+          # Prevents exposing terraform's STDOUT, STDERR
+          terraform_wrapper: false
+
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Plan
+        id: tf-plan
+        run: |
+          exitcode=0
+          terraform plan -detailed-exitcode -no-color -out tfplan || exitcode=$?
+
+          echo "exitcode=$exitcode" >> "$GITHUB_OUTPUT"
+
+          if [ $exitcode -eq 1 ]; then
+            echo "Terraform Plan Failed!"
+            exit 1
+          else
+            exit 0
+          fi
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: tfplan
+          path: tfplan
